### ISSUE TITLE
Not Clientside

### ISSUE THREAD

**Issue by DemonGamingLP** [Shardion/mods#1]
According to in-game and steam workshop, the mod is not client side anymore: 
![image](https://github.com/Shardion/mods/assets/66078541/630a8b58-9271-4259-9305-7c1ff5ee4e70)
![image](https://github.com/Shardion/mods/assets/66078541/b0e4734f-41dc-4dc6-9f15-2a5a814c91e0)

Should be a quick fix i hope!

**Comment by Shardion** [comment]
Fixed in 499779a. A hotfix for Clientside Lag Prevention including this commit, v2.0.1, has been published to the Steam Workshop.
